# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SecurityCloud' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'AFNetworking', '~> 3.0'  
  pod 'SDWebImage', '~>3.8'
  pod "MagicalRecord"
  pod 'Masonry'
  pod 'SVProgressHUD'
  pod 'IQKeyboardManager'
  pod 'MJExtension'
  pod 'MJRefresh'
  pod 'ESPictureBrowser'
  pod 'TZImagePickerController'
  # Pods for SecurityCloud

  target 'SecurityCloudTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SecurityCloudUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
