# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SecurityCloud' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'AFNetworking', '~> 3.0'  
  pod 'SDWebImage', '~>3.8'
  pod "MagicalRecord"
  pod 'Masonry'
  pod 'SVProgressHUD'
  pod 'IQKeyboardManager'
  pod 'MJExtension'
  pod 'MJRefresh'
  pod 'ESPictureBrowser'
  pod 'TZImagePickerController'
  pod 'DateTools'
  pod 'JPush'
  pod 'ActionSheetPicker-3.0'
  pod 'KZSmallVideoRecorder', '~> 1.0.4'
  pod "Qiniu", "~> 7.1"
  pod 'ZFPlayer'
  
  
  pod ‘UMengUShare/UI’
  
  
  # 集成微信(完整版14.4M)
  pod ‘UMengUShare/Social/WeChat'

  
  # 集成QQ(完整版7.6M)
  pod ‘UMengUShare/Social/QQ'
  # Pods for SecurityCloud

  target 'SecurityCloudTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SecurityCloudUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
